name: Build Container
on: [push] # You may want to trigger this Action on other things than a push.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main
    - name: get dockerfile
      env:
        TOKEN: ${{ secrets.repo_token }}
      run: |
        curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/Roussman/pytudes/main/DockerFile_appendix.dockerfile -o DockerFile_appendix.dockerfile

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        APPENDIX_FILE: DockerFile_appendix.dockerfile
